# Generated by Django 2.0.13 on 2020-02-13 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCommute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_title', models.CharField(max_length=30)),
                ('source_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('journey_frequency', models.IntegerField()),
                ('pref_gender', models.IntegerField()),
                ('pref_mode_travel', models.IntegerField()),
                ('start_time', models.DateTimeField(verbose_name=' Journey Start Time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
