# Generated by Django 2.0.13 on 2020-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_commute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycommute',
            name='journey_id',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
