# Generated by Django 2.0.13 on 2020-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_commute', '0002_dailycommute_journey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycommute',
            name='time_of_commute',
            field=models.TimeField(null=True, verbose_name='time of the day when commute takes place'),
        ),
        migrations.AlterField(
            model_name='dailycommute',
            name='journey_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailycommute',
            name='start_time',
            field=models.DateField(verbose_name='Journey Start date'),
        ),
    ]
