# Generated by Django 3.0.2 on 2020-01-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Joining Date')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
