# Generated by Django 3.0.2 on 2020-01-22 20:29

import API.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200122_0230'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', API.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sign Up Date'),
        ),
        migrations.CreateModel(
            name='DailyCommute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_title', models.CharField(max_length=30)),
                ('source_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name=' Journey Start Time')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
